baseurl = "http://dominicandevops.blog/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  
  # My information
  author = "Marvin Matoos"
  description = "This page is a blog about devops, ill be using it to review some solutions that ive either implemented at work or am learning to forward my career"
  bio = "Platform Engineer at WW International"
  twitter = "mjmatos_nps"
  copyright = "Marvin Matos"

[social]
  github = "https://github.com/54b3r"

[languages]
  [languages.en]
    title = "Dominican Devops Blog"
    subtitle = "A DevOps blog written by a Dominican"
    keywords = "devops,sre,platform,engineering,infrastructure,dominicandevops"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
