baseURL = "https://dominicandevops.blog"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "Dominican DevOps Blog"
disqusShortname = ""
googleAnalytics = ""
summaryLength = 40
pluralizeListTitles = false
enableemoji = true

[params]
    description = "A blog thats all things DevOps/SRE"
    googleSearch = ""
    adsense = ""
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page
    githubProfile = "54b3r/"

    tagsInHome = 40
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 10

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "This Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3
    
    [[menu.main]]
        name = "Author"
        url = "/author/"
        weight = 3